--Users table
CREATE TABLE IF NOT EXISTS User{
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	phone VARCHAR(10) UNIQUE NOT NULL,
	loyalty DOUBLE DEFAULT '0'
};

